# fly.toml file generated for lucaspickering-protohackers on 2022-09-12T12:26:02-04:00

app = "lucaspickering-protohackers"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
# protohackers is hosted in London
PRIMARY_REGION = "lhr"
RUST_LOG = "debug"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8000
processes = ["app"]
protocol = "tcp"
script_checks = []
[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"

[[services.ports]]
port = 8000

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
